########### build container (node)
FROM node:24-bookworm AS dubbingbuildnode
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY tsconfig.json ./
ADD src/ ./src/
RUN npm run build
# RUN ls -l

########### build container (python)
FROM nvidia/cuda:13.1.1-cudnn-devel-ubuntu24.04 AS dubbingbuildpython
WORKDIR /opt/venv

RUN apt update && apt install -y python3-venv ffmpeg sox git && rm -rf /var/lib/apt/lists/*

RUN touch F

RUN git clone https://github.com/ZalozbaDev/open-dubbing
RUN cd open-dubbing && python3 -m venv .
COPY docker/requirements_dubbing.txt open-dubbing/
RUN cd open-dubbing && /bin/bash -c 'source bin/activate && pip install -r requirements_dubbing.txt'
RUN cd open-dubbing && /bin/bash -c 'source bin/activate && pip install .'

########### runtime container
FROM nvidia/cuda:13.1.1-runtime-ubuntu24.04

LABEL com.nvidia.cuda.version="12.6"
LABEL license="Includes NVIDIA CUDA redistributables subject to NVIDIA EULA"

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /usr/app/src

RUN apt update && apt install -y python3 libpython3.12 ffmpeg sox nodejs npm && rm -rf /var/lib/apt/lists/*

RUN mkdir -p uploads && chown 1000:1000 uploads

RUN mkdir -p src/scripts && chown -R 1000:1000 src/

# venv übernehmen
COPY --chown=1000:1000 --from=dubbingbuildpython /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY --chown=1000:1000 package*.json ./
RUN npm ci --omit=dev

COPY --chown=1000:1000 --from=dubbingbuildnode /app/dist ./dist

COPY --chown=1000:1000 src/scripts/create_dubbing.sh src/scripts
COPY --chown=1000:1000 src/scripts/dubbing.sh        src/scripts

USER 1000

ENV NODE_ENV=production
ENV SERVER_MODE=DUBBING

CMD ["node", "dist/index.js"]
